//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RabbitMQ4Consumer.Verifications {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class VModelVerificationResult
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VModelVerificationResult()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RabbitMQ4Consumer.Verifications.VModelVerificationResult", typeof(VModelVerificationResult).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DifferentPRAVerificationDescription
        {
            get
            {
                return ResourceManager.GetString("DifferentPRAVerificationDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 1010.
        /// </summary>
        internal static string DifferentPRAVerificationId
        {
            get
            {
                return ResourceManager.GetString("DifferentPRAVerificationId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Different “PRA” value.
        /// </summary>
        internal static string DifferentPRAVerificationTitle
        {
            get
            {
                return ResourceManager.GetString("DifferentPRAVerificationTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DifferenttRearrangedDescription
        {
            get
            {
                return ResourceManager.GetString("DifferenttRearrangedDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 1310.
        /// </summary>
        internal static string DifferenttRearrangedId
        {
            get
            {
                return ResourceManager.GetString("DifferenttRearrangedId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Different “Rearranged” value.
        /// </summary>
        internal static string DifferenttRearrangedTitle
        {
            get
            {
                return ResourceManager.GetString("DifferenttRearrangedTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string KeyTestLevelVerificationDescription
        {
            get
            {
                return ResourceManager.GetString("KeyTestLevelVerificationDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 1901.
        /// </summary>
        internal static string KeyTestLevelVerificationId
        {
            get
            {
                return ResourceManager.GetString("KeyTestLevelVerificationId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The key tested by is incorrect.
        /// </summary>
        internal static string KeyTestLevelVerificationTitle
        {
            get
            {
                return ResourceManager.GetString("KeyTestLevelVerificationTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Location value cannot be null..
        /// </summary>
        internal static string LocationEmptyVerificationDescription
        {
            get
            {
                return ResourceManager.GetString("LocationEmptyVerificationDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 1101.
        /// </summary>
        internal static string LocationEmptyVerificationId
        {
            get
            {
                return ResourceManager.GetString("LocationEmptyVerificationId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Location is empty.
        /// </summary>
        internal static string LocationEmptyVerificationTitle
        {
            get
            {
                return ResourceManager.GetString("LocationEmptyVerificationTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The key must have test unless when the key Rearranged is &quot;Deferred&quot; or &quot;Terminated&quot; the key have no test case is ok..
        /// </summary>
        internal static string NoTestCaseVerificationDescription
        {
            get
            {
                return ResourceManager.GetString("NoTestCaseVerificationDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 1201.
        /// </summary>
        internal static string NoTestCaseVerificationId
        {
            get
            {
                return ResourceManager.GetString("NoTestCaseVerificationId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The key have no any test case.
        /// </summary>
        internal static string NoTestCaseVerificationTitle
        {
            get
            {
                return ResourceManager.GetString("NoTestCaseVerificationTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to RS has nothing traced from, SFS has 0 or 1 traced from, SSFS has 0 or 1 traced from, DS has 0 or 1 traced from.
        /// </summary>
        internal static string ParentRequirementVerificationDescription
        {
            get
            {
                return ResourceManager.GetString("ParentRequirementVerificationDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 1401.
        /// </summary>
        internal static string ParentRequirementVerificationId
        {
            get
            {
                return ResourceManager.GetString("ParentRequirementVerificationId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The key has invalid traced from.
        /// </summary>
        internal static string ParentRequirementVerificationTitle
        {
            get
            {
                return ResourceManager.GetString("ParentRequirementVerificationTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Planned but not realized (both vertical and horizontal).
        /// </summary>
        internal static string PlannedButNotRealizedVerificationDescription
        {
            get
            {
                return ResourceManager.GetString("PlannedButNotRealizedVerificationDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 1701.
        /// </summary>
        internal static string PlannedButNotRealizedVerificationId
        {
            get
            {
                return ResourceManager.GetString("PlannedButNotRealizedVerificationId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Planned but not realized.
        /// </summary>
        internal static string PlannedButNotRealizedVerificationTitle
        {
            get
            {
                return ResourceManager.GetString("PlannedButNotRealizedVerificationTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to If a requirement&apos;s PRA value is &quot;Yes&quot;, all of its related requirements or test cases&apos; PRA value should be &quot;Yes&quot;, vice versa..
        /// </summary>
        internal static string PRADifferentVerificationDescription
        {
            get
            {
                return ResourceManager.GetString("PRADifferentVerificationDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 1001.
        /// </summary>
        internal static string PRADifferentVerificationId
        {
            get
            {
                return ResourceManager.GetString("PRADifferentVerificationId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Different PRA value.
        /// </summary>
        internal static string PRADifferentVerificationTitle
        {
            get
            {
                return ResourceManager.GetString("PRADifferentVerificationTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PRADifferentWithParentRequirementDescription
        {
            get
            {
                return ResourceManager.GetString("PRADifferentWithParentRequirementDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 1004.
        /// </summary>
        internal static string PRADifferentWithParentRequirementId
        {
            get
            {
                return ResourceManager.GetString("PRADifferentWithParentRequirementId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Differnet PRA with parent-requirement.
        /// </summary>
        internal static string PRADifferentWithParentRequirementTitle
        {
            get
            {
                return ResourceManager.GetString("PRADifferentWithParentRequirementTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PRADifferentWithSubRequirmentDescription
        {
            get
            {
                return ResourceManager.GetString("PRADifferentWithSubRequirmentDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 1002.
        /// </summary>
        internal static string PRADifferentWithSubRequirmentId
        {
            get
            {
                return ResourceManager.GetString("PRADifferentWithSubRequirmentId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Different PRA with sub-requirment.
        /// </summary>
        internal static string PRADifferentWithSubRequirmentTitle
        {
            get
            {
                return ResourceManager.GetString("PRADifferentWithSubRequirmentTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PRADifferentWithTestCaseVerificationDescription
        {
            get
            {
                return ResourceManager.GetString("PRADifferentWithTestCaseVerificationDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 1003.
        /// </summary>
        internal static string PRADifferentWithTestCaseVerificationId
        {
            get
            {
                return ResourceManager.GetString("PRADifferentWithTestCaseVerificationId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Different PRA with test case.
        /// </summary>
        internal static string PRADifferentWithTestCaseVerificationTitle
        {
            get
            {
                return ResourceManager.GetString("PRADifferentWithTestCaseVerificationTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to PRA value cannot be null..
        /// </summary>
        internal static string PRAEmptyVerificationDescription
        {
            get
            {
                return ResourceManager.GetString("PRAEmptyVerificationDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 1001.
        /// </summary>
        internal static string PRAEmptyVerificationId
        {
            get
            {
                return ResourceManager.GetString("PRAEmptyVerificationId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to PRA is emtpy.
        /// </summary>
        internal static string PRAEmptyVerificationTitle
        {
            get
            {
                return ResourceManager.GetString("PRAEmptyVerificationTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Realization but not planned (both vertical and horizontal).
        /// </summary>
        internal static string RealizationButNotPlannedVerificationDescription
        {
            get
            {
                return ResourceManager.GetString("RealizationButNotPlannedVerificationDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 1801.
        /// </summary>
        internal static string RealizationButNotPlannedVerificationId
        {
            get
            {
                return ResourceManager.GetString("RealizationButNotPlannedVerificationId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Realization but not planned.
        /// </summary>
        internal static string RealizationButNotPlannedVerificationTitle
        {
            get
            {
                return ResourceManager.GetString("RealizationButNotPlannedVerificationTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string RearrangedDifferentWithParentRequirementVerificationDescription
        {
            get
            {
                return ResourceManager.GetString("RearrangedDifferentWithParentRequirementVerificationDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 1302.
        /// </summary>
        internal static string RearrangedDifferentWithParentRequirementVerificationId
        {
            get
            {
                return ResourceManager.GetString("RearrangedDifferentWithParentRequirementVerificationId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string RearrangedDifferentWithParentRequirementVerificationTitle
        {
            get
            {
                return ResourceManager.GetString("RearrangedDifferentWithParentRequirementVerificationTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string RearrangedDifferentWithSubRequirementVerificationDescription
        {
            get
            {
                return ResourceManager.GetString("RearrangedDifferentWithSubRequirementVerificationDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 1301.
        /// </summary>
        internal static string RearrangedDifferentWithSubRequirementVerificationId
        {
            get
            {
                return ResourceManager.GetString("RearrangedDifferentWithSubRequirementVerificationId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string RearrangedDifferentWithSubRequirementVerificationTitle
        {
            get
            {
                return ResourceManager.GetString("RearrangedDifferentWithSubRequirementVerificationTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to If the rearranged is &quot;Terminated&quot; or &quot;Deferred&quot;, Status is released is invalid otherwise is ok。.
        /// </summary>
        internal static string RearrangedWithInvalidStatusDescription
        {
            get
            {
                return ResourceManager.GetString("RearrangedWithInvalidStatusDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 1303.
        /// </summary>
        internal static string RearrangedWithInvalidStatusId
        {
            get
            {
                return ResourceManager.GetString("RearrangedWithInvalidStatusId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Status should not be released when the key is &quot;Terminated&quot; or &quot;Deferred&quot;..
        /// </summary>
        internal static string RearrangedWithInvalidStatusTitle
        {
            get
            {
                return ResourceManager.GetString("RearrangedWithInvalidStatusTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SourceVerificationDescription
        {
            get
            {
                return ResourceManager.GetString("SourceVerificationDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 2001.
        /// </summary>
        internal static string SourceVerificationId
        {
            get
            {
                return ResourceManager.GetString("SourceVerificationId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The key traced from is incorrect.
        /// </summary>
        internal static string SourceVerificationTitle
        {
            get
            {
                return ResourceManager.GetString("SourceVerificationTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The right status of requirements and test cases should be &quot;released&quot;..
        /// </summary>
        internal static string StatusVerificationDescription
        {
            get
            {
                return ResourceManager.GetString("StatusVerificationDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 1601.
        /// </summary>
        internal static string StatusVerificationId
        {
            get
            {
                return ResourceManager.GetString("StatusVerificationId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Wrong Status.
        /// </summary>
        internal static string StatusVerificationTitle
        {
            get
            {
                return ResourceManager.GetString("StatusVerificationTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to RS has 1-n SFS, SFS has 1-n SSFS, SSFS has 0-n DS, DS has nothing traced to.
        /// </summary>
        internal static string SubRequirementVerificationDescription
        {
            get
            {
                return ResourceManager.GetString("SubRequirementVerificationDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 1501.
        /// </summary>
        internal static string SubRequirementVerificationId
        {
            get
            {
                return ResourceManager.GetString("SubRequirementVerificationId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid traced to.
        /// </summary>
        internal static string SubRequirementVerificationTitle
        {
            get
            {
                return ResourceManager.GetString("SubRequirementVerificationTitle", resourceCulture);
            }
        }
    }
}
